# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  
  
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures: 2020
  ecmaVersion: 2020
  sourceType: module
  
rules:
  no-console: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
