# Name of workflow
name: Node CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  build:

    # The type of machine to run the job on
    runs-on: ubuntu-latest

    strategy:
      # Node versions list
      matrix:
        node-version: [v14.9.0]

    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Use Node.js v14.9.0
        # Configures the node version used on GitHub-hosted runners
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1
        # The Node.js version to configure
        with:
          node-version: v14.9.0
      - name: npm install, build
        # Install and build project
        run: |
          make install
        # Add environment variables
        env:
          CI: true
      - name: Run linter
        # Run Linter
        run: |
          make lint
      - name: Run tests
        run: |
         make test
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{f97bfde1d4efe5bc8fb3fb07aec4ceed5782753e7a18249bf13cf7880537e8af}}
        with:
          coverageCommand: make test-coverage
          debug: true